baseURL: https://ewbscu.github.io/
languageCode: en-us
title: "Engineers Without Borders"
theme: "hugo-universal-theme"

params:
  style: blue
  disabled_logo: false
  logo_text: "EWB SCU"
  logo: "img/logo.png"
  logo_small: "img/logo.png"
  mainSections: ["projects","our partner communities","travel updates", "club updates","project updates"]
  carouselHomepage:
    enable: false
    auto_play: true
    slide_speed: 2000
    pagination_speed: 1000
  see_more:
    enable: true
    title: Engineers Without Borders
    subtitle: Santa Clara University
    link_url: "#"
    link_text: "LEARN MORE"
  description_header: >
    We apply technical knowledge to solve pressing challenges in developing nations, 
    while providing SCU students with real project experience.
  description: >
    With an active long-term project in Nyange, Rwanda, students experience the entire project process — 
    from identifying a problem to ideating solutions to implementing the final product. 
    Throughout the academic year, students communicate with the partner community to address their needs, 
    design and prototype solutions, and iterate and test designs. These projects, though entirely student run, 
    are held to the EWB National model and on-campus faculty reviews. This ensures project sustainability, 
    and reinforces the importance of thorough design practices.
  features:
    enable: true
    cols: 2

menu:
  main: 
    - name: Home
      identifier: menu.home
      url: /
      weight: 1

    - name: 'Our Team'
      identifier: menu.team
      url: ""
      weight: 2
    - name: 'Officer Team'
      url: /officers
      weight: 1
      parent: menu.team
    - name: 'Ministries'
      url: /ministries
      weight: 2
      parent: menu.team
    - name: 'Advisors'
      url: /Advisors
      weight: 3
      parent: menu.team
    - name: 'Alumni'
      url: /Alumni
      weight: 4
      parent: menu.team
    - name: 'Partners'
      url: /partners
      weight: 5
      parent: menu.team

    - name: 'About'
      identifier: menu.about
      url: ""
      weight: 3
    - name: 'What We Do'
      url: /what-we-do
      weight: 1
      parent: menu.about
    - name: 'Projects'
      url: /projects
      weight: 2
      parent: menu.about
    - name: 'Our Partner Communities'
      url: /our-partner-communities
      weight: 3
      parent: menu.about
    - name: 'Voluntourism'
      url: /voluntourism
      weight: 4
      parent: menu.about

    - name: 'Updates'
      identifier: menu.updates
      url: ""
      weight: 3
    - name: 'Travel Updates'
      url: /travel-updates
      weight: 1
      parent: menu.updates
    - name: 'Club Updates'
      url: /club-updates
      weight: 2
      parent: menu.updates
    - name: 'Project Updates'
      url: /project-updates
      weight: 3
      parent: menu.updates

    - name: 'Take Action'
      identifier: menu.action
      url: ""
      weight: 4
    - name: '5k for $5k'
      url: /5k-for-5k
      weight: 1
      parent: menu.action
    - name: 'Contact Us'
      url: /contact
      weight: 2
      parent: menu.action